/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as AtelierStudioRouteImport } from './routes/atelier-studio'
import { Route as BagRouteImport } from './routes/bag'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as September14RouteImport } from './routes/september-14'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PieceSlugRouteImport } from './routes/piece.$slug'
import { Route as StudioSettingsRouteImport } from './routes/studio.settings'
import { Route as StudioUploadRouteImport } from './routes/studio.upload'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierStudioRoute = AtelierStudioRouteImport.update({
  id: '/atelier-studio',
  path: '/atelier-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const September14Route = September14RouteImport.update({
  id: '/september-14',
  path: '/september-14',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PieceSlugRoute = PieceSlugRouteImport.update({
  id: '/piece/$slug',
  path: '/piece/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioUploadRoute = StudioUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => StudioRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/atelier': typeof AtelierRoute
  '/atelier-studio': typeof AtelierStudioRoute
  '/bag': typeof BagRoute
  '/collection': typeof CollectionRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/reels': typeof ReelsRoute
  '/september-14': typeof September14Route
  '/studio': typeof StudioRouteWithChildren
  '/piece/$slug': typeof PieceSlugRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/upload': typeof StudioUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/atelier': typeof AtelierRoute
  '/atelier-studio': typeof AtelierStudioRoute
  '/bag': typeof BagRoute
  '/collection': typeof CollectionRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/reels': typeof ReelsRoute
  '/september-14': typeof September14Route
  '/studio': typeof StudioRouteWithChildren
  '/piece/$slug': typeof PieceSlugRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/upload': typeof StudioUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/atelier': typeof AtelierRoute
  '/atelier-studio': typeof AtelierStudioRoute
  '/bag': typeof BagRoute
  '/collection': typeof CollectionRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/reels': typeof ReelsRoute
  '/september-14': typeof September14Route
  '/studio': typeof StudioRouteWithChildren
  '/piece/$slug': typeof PieceSlugRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/upload': typeof StudioUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/atelier'
    | '/atelier-studio'
    | '/bag'
    | '/collection'
    | '/journal'
    | '/login'
    | '/reels'
    | '/september-14'
    | '/studio'
    | '/piece/$slug'
    | '/studio/settings'
    | '/studio/upload'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/atelier'
    | '/atelier-studio'
    | '/bag'
    | '/collection'
    | '/journal'
    | '/login'
    | '/reels'
    | '/september-14'
    | '/studio'
    | '/piece/$slug'
    | '/studio/settings'
    | '/studio/upload'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/atelier'
    | '/atelier-studio'
    | '/bag'
    | '/collection'
    | '/journal'
    | '/login'
    | '/reels'
    | '/september-14'
    | '/studio'
    | '/piece/$slug'
    | '/studio/settings'
    | '/studio/upload'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AtelierRoute: typeof AtelierRoute
  AtelierStudioRoute: typeof AtelierStudioRoute
  BagRoute: typeof BagRoute
  CollectionRoute: typeof CollectionRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  ReelsRoute: typeof ReelsRoute
  September14Route: typeof September14Route
  StudioRoute: typeof StudioRouteWithChildren
  PieceSlugRoute: typeof PieceSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier-studio': {
      id: '/atelier-studio'
      path: '/atelier-studio'
      fullPath: '/atelier-studio'
      preLoaderRoute: typeof AtelierStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/september-14': {
      id: '/september-14'
      path: '/september-14'
      fullPath: '/september-14'
      preLoaderRoute: typeof September14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piece/$slug': {
      id: '/piece/$slug'
      path: '/piece/$slug'
      fullPath: '/piece/$slug'
      preLoaderRoute: typeof PieceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/settings': {
      id: '/studio/settings'
      path: '/settings'
      fullPath: '/studio/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/upload': {
      id: '/studio/upload'
      path: '/upload'
      fullPath: '/studio/upload'
      preLoaderRoute: typeof StudioUploadRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioSettingsRoute: typeof StudioSettingsRoute
  StudioUploadRoute: typeof StudioUploadRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioSettingsRoute: StudioSettingsRoute,
  StudioUploadRoute: StudioUploadRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AtelierRoute: AtelierRoute,
  AtelierStudioRoute: AtelierStudioRoute,
  BagRoute: BagRoute,
  CollectionRoute: CollectionRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  ReelsRoute: ReelsRoute,
  September14Route: September14Route,
  StudioRoute: StudioRouteWithChildren,
  PieceSlugRoute: PieceSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
